import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

export const skills=[
  {title:'Programming',level:'Working knowledge',skills:['C++','Python','PHP','Java','JavaScript']},
  {title:'Web development',level:'Practical exposure',skills:['HTML','CSS','JavaScript','PHP','Angular']},
  {title:'Networking',level:'Practical exposure',skills:['Cisco Packet Tracer','RIP, OSPF and EIGRP','Router and server configuration','Network troubleshooting','RJ45 termination']},
  {title:'Systems and IT',level:'Familiar with',skills:['System analysis and design','Information systems','Hardware and software troubleshooting','Windows troubleshooting','Technical support']},
  {title:'GIS and data',level:'Practical exposure',skills:['GIS tools','QField','GeoODK Collect','GPS and location data','Field data collection']},
  {title:'Database',level:'Working knowledge',skills:['MySQL','SQL','Database design']}
];

@Component({selector:'app-root',standalone:true,imports:[RouterOutlet,RouterLink,RouterLinkActive],template:`
  <header><a class="brand" routerLink="/about">MS<span>.</span></a><button class="menu" type="button" (click)="open=!open" [attr.aria-expanded]="open">Menu</button><nav [class.open]="open"><a routerLink="/about" routerLinkActive="active" (click)="open=false">About</a><a routerLink="/skills" routerLinkActive="active" (click)="open=false">Skills</a><a routerLink="/projects" routerLinkActive="active" (click)="open=false">Projects</a><a routerLink="/contact" routerLinkActive="active" (click)="open=false">Contact</a></nav></header><router-outlet></router-outlet><footer><a class="brand" routerLink="/about">MS<span>.</span></a><small>Copyright {{year}} Makabongwe Simelane</small><a routerLink="/about">Back to top</a></footer>`})
export class AppComponent { open=false; year=new Date().getFullYear(); }

@Component({standalone:true,imports:[CommonModule,RouterLink],template:`
  <main><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">COMPUTER SCIENCE GRADUATE - ESWATINI</p><h1>Hi, I'm <em>Makabongwe</em> Simelane.</h1><p class="lead">IT Enthusiast - Aspiring Software and IT Professional. I enjoy turning curiosity into useful technology.</p><p><a class="button" routerLink="/projects">View my projects</a><a class="link" routerLink="/contact">Contact me</a></p><small class="available">Open to graduate, internship and entry-level IT opportunities</small></div><div class="profile"><img src="assets/images/s19.jpg" alt="Makabongwe Simelane"><aside><b>2026</b> Diploma in<br>Computer Science</aside></div></section>
  <section class="wrap"><p class="eyebrow">ABOUT ME</p><div class="heading"><h2>A curious mind, grounded in practical technology.</h2><p>I am a positive, inquisitive and motivated Computer Science graduate who is always eager to learn, explore new technologies and expand my knowledge.</p></div><div class="intro"><p>From a young age, I have been fascinated by the power of technology and its ability to solve problems, improve processes, connect people and transform the world. This passion inspired me to pursue a Diploma in Computer Science at Eswatini College of Technology.</p><p>Throughout my studies, I developed a strong foundation in programming and information technology through coursework, assignments, projects and internship experience. I approach responsibilities with passion, commitment and a willingness to contribute.</p><small>Born 6 June 2002</small></div><div class="timeline"><article *ngFor="let item of education"><b>{{item.year}}</b><span></span><p>{{item.text}}</p></article></div><div class="experience"><div><p class="eyebrow">TECHNICAL BACKGROUND</p><h3>Learning by building, analysing and troubleshooting.</h3></div><p>Working knowledge of C++, Python, PHP, Java, JavaScript, HTML and CSS, with practical exposure to web development, information systems design, database systems, networking, GIS, data collection and IT support.</p></div></section>
  <section class="gallery-section"><div class="wrap"><p class="eyebrow">DATAMATICS INTERNSHIP</p><div class="heading"><h2>GIS and field data collection experience.</h2><p>At Datamatics, I gained practical exposure to GIS tools, IT projects, information systems and field data collection.</p></div><div class="gallery gis-gallery"><figure *ngFor="let image of gis"><img [src]="'assets/images/'+image.file" [alt]="image.caption"><figcaption>{{image.caption}}</figcaption></figure></div><p class="reading">A GIS-based data collection exercise in Matsapha developed my experience of location-based data collection in a real working environment and strengthened collaboration, communication, accuracy, time management and adaptability.</p></div></section>
  <section class="networking wrap"><p class="eyebrow">NETWORKING EXPERIENCE</p><div class="heading"><h2>Practical exposure to connected systems.</h2><p>Networking study that connected configuration, communication and problem solving.</p></div><div class="network-copy"><p>During my Computer Science studies, I gained practical exposure to configuring network devices, understanding network communication and troubleshooting network-related problems. I worked with Cisco Packet Tracer and gained exposure to RIP, OSPF and EIGRP.</p><p>I developed an understanding of routing, path determination and how data packets move from a local area network to other networks. Practical tasks included server and router configuration, installing network ports, troubleshooting and terminating Ethernet cables using RJ45 connectors.</p></div><div class="gallery network-gallery"><figure *ngFor="let image of networking"><img [src]="'assets/images/'+image" alt="Networking practical work"><figcaption>Networking practical work</figcaption></figure></div></section></main>`})
export class AboutPageComponent { education=[{year:'2016',text:'Started high school at Evelyn Baring High School'},{year:'2020',text:'Completed high school'},{year:'2023',text:'Started Diploma in Computer Science at ECOT'},{year:'2026',text:'Completed Diploma in Computer Science'}]; gis=[{file:'s6.jpg',caption:'GIS Field Data Collection'},{file:'s7.jpg',caption:'Field Survey Activity'},{file:'s8.jpg',caption:'Location-Based Data Collection'}]; networking=['s9.jpg','s10.jpg','s11.jpg','s12.jpg','s13.jpg','s14.jpg','s15.jpg','s16.jpg','s1.jpg','s2.jpg','s3.jpg','s4.jpg','s5.jpg','p1.jpg','p4.jpg']; }

@Component({standalone:true,imports:[CommonModule],template:`<main class="page-main wrap"><p class="eyebrow">SKILLS</p><div class="heading"><h2>A growing, practical technical toolkit.</h2><p>Experience gained through study, hands-on assignments, projects and internship exposure - always with room to learn more.</p></div><div class="cards"><article *ngFor="let group of groups"><div class="skill-title"><h3>{{group.title}}</h3><i>{{group.level}}</i></div><ul><li *ngFor="let skill of group.skills">{{skill}}</li></ul></article></div></main>`})
export class SkillsPageComponent { groups=skills; }

@Component({standalone:true,imports:[CommonModule],template:`<main class="page-main wrap"><p class="eyebrow">SELECTED PROJECTS</p><div class="heading"><h2>Academic work with real-world intent.</h2><p>Projects that helped me move from theory into thoughtful system design and implementation.</p></div><div class="projects"><article *ngFor="let project of projects;let n=index"><div class="art" [class.orange]="n===1"><span>{{project.label}}</span><b>{{n===0?'O':n===1?'#':'+'}}</b></div><div class="project-body"><i>0{{n+1}}</i><h3>{{project.title}}</h3><p>{{project.description}}</p><p class="goal"><b>GOAL</b>{{project.goal}}</p><div class="tags"><span *ngFor="let feature of project.features">{{feature}}</span></div><p><b>Contribution:</b> {{project.role}}</p><a *ngIf="project.url" class="project-link" [href]="project.url" target="_blank" rel="noopener noreferrer">View Website</a></div></article></div></main>`})
export class ProjectsPageComponent { projects=[{label:'LOCATION-BASED SYSTEM',title:'Geolocation Attendance System',description:'A location-based attendance management system designed to modernise student attendance through geolocation technology instead of relying entirely on paper-based attendance.',goal:'Reduce reliance on paper-based attendance and support more reliable attendance management.',features:['Location-based attendance','Student attendance management','Attendance validation'],role:'Contributed to applying location-based technology to a practical attendance problem.',url:'https://ecot.free.je/login.php'},{label:'FINAL-YEAR INFORMATION SYSTEM',title:'Yadah Technologies Client Service and Employee Deployment System',description:'A team-developed information system for Yadah Technologies focused on client service management and employee deployment through a centralised system.',goal:'Organise client service activities and employee deployment.',features:['Information systems design','Database management','Web development'],role:'Worked on system analysis, design and business-process understanding.'},{label:'WEB DEVELOPMENT',title:'Yadah Technologies Website',description:'A website developed for Yadah Technologies as practical web development experience, presenting organisation information through a structured online presence.',goal:'Provide a clear, accessible online presence for the organisation.',features:['Organisation information','Structured online presence'],role:'Developed the website as practical web development work.',url:'https://makabongwe787.github.io/yadahwebsite/about-us.html'},{label:'WORKFORCE MANAGEMENT',title:'Employee Attendance System',description:'A workforce attendance system where employees clock in when they arrive at work and clock out when they leave. It also helps employees record and track pending and completed projects.',goal:'Provide a clear record of employee attendance and project progress in one system.',features:['Employee clock-in and clock-out','Attendance records','Pending projects','Completed projects'],role:'Developed a practical system for attendance tracking and project-status recording.',url:'https://datamatics.dev/index.php/signin'}]; }

@Component({standalone:true,imports:[ReactiveFormsModule],template:`<main class="contact"><div class="wrap contact-grid"><div><p class="eyebrow">CONTACT</p><h2>Let's build something meaningful.</h2><p>I am open to opportunities where I can apply my technical knowledge, continue learning and contribute to meaningful technology projects.</p><small>Email and professional profile links can be added here once confirmed.</small></div><form [formGroup]="form" (ngSubmit)="send()"><label>Your name<input formControlName="name" placeholder="Your name"></label><label>Email address<input type="email" formControlName="email" placeholder="you@example.com"></label><label>Subject<input formControlName="subject" placeholder="How can I help?"></label><label>Message<textarea formControlName="message" placeholder="Tell me about the opportunity..."></textarea></label><button class="button" [disabled]="form.invalid||sending">{{sending?'Sending...':'Send message'}}</button><p [class.error]="error">{{status}}</p></form></div></main>`})
export class ContactPageComponent { http=inject(HttpClient); fb=inject(FormBuilder); sending=false; error=false; status=''; form=this.fb.nonNullable.group({name:['',Validators.required],email:['',[Validators.required,Validators.email]],subject:['',Validators.required],message:['',Validators.required]}); send(){if(this.form.invalid)return;this.sending=true;this.error=false;this.status='Sending your message...';this.http.post('http://localhost:8000/api/contact',this.form.getRawValue()).subscribe({next:()=>{this.status='Message sent - thank you.';this.form.reset();this.sending=false},error:()=>{this.status='Unable to send right now. Please try again later.';this.error=true;this.sending=false}})} }
